# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e4b05ef30925f2b0c0fddc4e6f4b5dd3ddf9bc53749cb4abc9ee3dfb365ed46866f577d00b12a324c9f38b9aba01925c48f95672a59f01f7775651beacab7c

test:
  secret_key_base: 37e2e34c8f5cb7ea4ce4a4d7f9dfd466b36f4ecfd4dcfc6e9a7c6913f8766a49fed0989b3bf159e7a4283c8b8e8f5fe5581bf6868e3bed15ebcc0bd7e2b0fcaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
